\documentclass{article}
\title{A probabilistic cutoff for calling peaks}

\usepackage[text={178mm,230mm},centering]{geometry}
\usepackage{Sweave}

\SweaveOpts{keep.source=TRUE,eps=FALSE,pdf=TRUE,width=9,height=11,prefix.string=figs/figs-mousepeaks}
\setkeys{Gin}{width=0.98\textwidth}

\begin{document}

\maketitle

\raggedright

<<setup,echo=FALSE,results=hide>>=

library(chipseq)
library(lattice)
## library(hexbin)
## library(latticeExtra)

load("myodMyo.rda")
load("myodFibro.rda")

set.seed(20081008)


islandDepthSummary <- function(x, g = extendReads(x))
{
    s <- slice(coverage(g, 1, max(end(g))), lower = 1)
    tab <- table(viewMaxs(s))
    ans <- data.frame(depth = as.numeric(names(tab)), count = as.numeric(tab))
    ans
}

plotDepthDistribution <- 
    function(data, chr = "chr1", depth.cutoff = 20, fit = TRUE, ...)
{
    xyplot(log(count) ~ depth | lane + chromosome, data, 
           subset = (chromosome %in% chr & depth <= depth.cutoff),
           main = sprintf("Distribution of island depths (%s)", chr),
           layout = c(length(chr), nlevels(data$lane)), 
           pch = 16, type = c("p", "g"), as.table = TRUE,
           strip = FALSE, strip.left = TRUE, # aspect = 0.4,
           panel = if (fit) function(x, y, ...) {
               lambda <- 2 * exp(y[2]) / exp(y[1])
               null.est <- function(xx) {
                   xx * log(lambda) - lambda - lgamma(xx + 1)
               }
               log.N.hat <- null.est(1) - y[1] # both already log-transformed
               panel.lines(1:10, -log.N.hat + null.est(1:10))
               panel.xyplot(x, y, ...)
           } else function(x, y, ...) {
               panel.lmline(x[1:2], y[1:2])
               panel.xyplot(x, y, ...)
           }, ...)
}


@ 


\section*{Depth distribution over all lanes}


<<>>=

myodMyoDepth <- 
    summarizeReads(myodMyo, 
                   summary.fun = islandDepthSummary)

plotDepthDistribution(myodMyoDepth, chr = "chr1", fit = FALSE)

@ 

\newpage

\begin{center}
<<fig=TRUE,echo=FALSE>>=
plot(trellis.last.object())
@ 
\end{center}



\newpage

\section*{Combining myotube and myoblast lanes}


<<>>=

seqRanges <- lapply(myodMyo, extendReads)

combinedMyo <- 
    list(cblasts = combineLanes(seqRanges[c("1","3","6")]),
         ctubes = combineLanes(seqRanges[c("2","4","7")]))

combinedMyoDepth <- 
    summarizeReads(combinedMyo, 
                   summary.fun = function(x) {
                       islandDepthSummary(g = x)
                   })
                   
plotDepthDistribution(combinedMyoDepth, chr = "chr1", fit = FALSE)


@ 

\newpage

\begin{center}
<<fig=TRUE,echo=FALSE>>=
plot(trellis.last.object())
@ 
\end{center}


\newpage


\section*{A null model for island depths}

Consider a slightly different problem:
\begin{itemize}
\item For each extended read $[a_i, b_i]$, where $a_i < b_i$ and $b_i
  - a_i = 200$, let $X_i$ be the number of other start points $a_j \in
  [a_i, b_i], j \neq i$.
\item $X_i = k$ implies island of depth $k$ (or more).
\item island of depth $k$ implies $X_i = k$ for some $i$ in that island.
\end{itemize}
We will pretend that $X_i$-s are a reasonable first approximation to
island depths.  Note that the following analysis applies directly to
the number of reads (rather than depth) per island as well.


$X_i \sim Poisson(\lambda)$ for some unknown $\lambda$ (approximately
$200 N / G$, where $N$ is the number of reads, and $G$ is the length
of the genome).  
\[
f_\lambda(x) = P(X_i = x) = \lambda^x \frac{e^{-\lambda}}{x!}
\]
so
\[
\log(f_\lambda(x)) = -\lambda + x \log \lambda - \log \Gamma(x+1)
\]
The shape of this function depends on $\lambda$.  Note that 
\[
\frac{f_\lambda(2)}{f_\lambda(1)} = \lambda/2 
\]
so a crude estimate of $\lambda$ is
\[
\hat \lambda = 2 X_2 / X_1
\]
Using this as a more sophisticated estimate of the null distribution,
we get
<<>>=

plotDepthDistribution(myodMyoDepth, chr = "chr1", fit = TRUE,
                      ylim = c(0, 12))

@ 

\newpage

\begin{center}
<<fig=TRUE,echo=FALSE>>=
plot(trellis.last.object())
@ 
\end{center}


\newpage

<<>>=

plotDepthDistribution(combinedMyoDepth, chr = "chr1", fit = TRUE,
                      ylim = c(0, 12))

@ 

\newpage

\begin{center}
<<fig=TRUE,echo=FALSE>>=
plot(trellis.last.object())
@ 
\end{center}


\section*{Fibroblast run}


<<>>=

myodFibroDepth <- 
    summarizeReads(myodFibro,
                   summary.fun = islandDepthSummary)

plotDepthDistribution(myodFibroDepth, chr = "chr1", fit = TRUE,
                      ylim = c(0, 12))


@ 

\newpage

\begin{center}
<<fig=TRUE,echo=FALSE>>=
plot(trellis.last.object())
@ 
\end{center}


\section*{How do we do in simulation?}


<<>>=
load("simulatedReads.rda")

subsim <- 
    list(sim = list(chr1 = list("+" = sample(simulatedReads$chr1$"+", 5e5), 
                                "-" = integer(0)),
                    chr2 = list("+" = sample(simulatedReads$chr2$"+", 5e5), 
                                "-" = integer(0))))



simulationDepth <- 
    summarizeReads(subsim, 
                   summary.fun = islandDepthSummary)

plotDepthDistribution(simulationDepth, chr = c("chr1", "chr2"), fit = TRUE)

@ 


\newpage

\begin{center}
<<fig=TRUE,echo=FALSE>>=
plot(trellis.last.object())
@ 
\end{center}


\end{document}
